baseURL = "https://cjj203.github.io/"
languageCode = "zh-cn"
title = "CaiJJ's Blog"
theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
  defaultTheme = "auto"
  showReadingTime = true
  showCodeCopyButtons = true
  showToc = true
  math = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
